version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data:/data/db

  api: 
    build: ./server
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  web:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - api
    environment:
      - API_HOST=http://api:8080
